#!/usr/bin/env python3
"""Canonical research-output orchestrator for eyetrack.

Goal
----
Produce a stable, paper-oriented research output bundle for the eye-tracking repo,
while preserving the content expectations that were previously associated with an
`analysis-2` / `research_bundle` output folder.

Pipeline
--------
1) batch_aoi_metrics.py
2) optimize_aoi_outputs.py
3) summarize_aoi_by_condition_group.py
4) model_aoi_lmm_allocation.py
5) model_aoi_two_part.py (optional, when scene features are available)
6) aoi_distribution_diagnostics.py

Outputs
-------
results/research_bundle/
  01_AOI与描述统计/
    organized_outputs/
    condition_group_summary/
  02_LMM模型/
    allocation_lmm/
    allocation_lmm_visuals/
  03_TwoPart模型/
    two_part_models/
  04_诊断信息/
  05_colab说明/
  06_说明与报告/
  00_AOI原始批处理/
"""

from __future__ import annotations

import argparse
import shlex
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = REPO_ROOT / "scripts"

TASK1_DIRNAME = "01_AOI与描述统计"
TASK2_DIRNAME = "02_LMM模型"
TASK3_DIRNAME = "03_TwoPart模型"
DIAG_DIRNAME = "04_诊断信息"
COLAB_DIRNAME = "05_colab说明"
REPORTS_DIRNAME = "06_说明与报告"
RAW_BATCH_DIRNAME = "00_AOI原始批处理"


def run(cmd: list[str]):
    print("[run]", " ".join(shlex.quote(str(x)) for x in cmd))
    subprocess.check_call(cmd, cwd=str(REPO_ROOT))


def write_structure_readme(
    out_root: Path,
    task1: Path,
    task2: Path,
    task3: Path,
    diag: Path,
    raw_batch: Path,
    reports: Path,
    colab: Path,
    autogenerated_scene_features: Path | None,
    analysis_csv: Path | None,
):
    lines = [
        "eyetrack 研究输出目录说明",
        "",
        f"总目录: {out_root.name}",
        "",
        "推荐查看顺序:",
        f"1. {task1.name}/  -> AOI整理结果 + 分组描述统计",
        f"2. {task2.name}/  -> allocation LMM结果 + 可视化",
        f"3. {task3.name}/  -> two-part model结果（若已生成）",
        f"4. {diag.name}/  -> 分布/有效率/重叠等诊断",
        f"5. {raw_batch.name}/ -> 原始批处理导出（底层表格与overlay）",
        "",
        "子目录说明:",
        f"- {task1.name}/organized_outputs/: optimize_aoi_outputs.py 整理后的AOI结果",
        f"- {task1.name}/condition_group_summary/: WWR × Complexity × Group 描述统计汇总",
        f"- {task2.name}/allocation_lmm/: allocation LMM 模型输出",
        f"- {task2.name}/allocation_lmm_visuals/: 面向解释的 LMM 图形",
        f"- {task3.name}/two_part_models/: two-part 模型结果",
        f"- {diag.name}/distribution/: AOI 分布诊断",
        f"- {raw_batch.name}/: batch_aoi_metrics.py 原始输出",
    ]
    if autogenerated_scene_features:
        lines.append(f"- 自动生成 scene_features: {autogenerated_scene_features.name}")
    if analysis_csv:
        lines.append(f"- 合并分析表: {analysis_csv.name}")
    lines += [
        "",
        "兼容说明:",
        "- 旧文档中的 task1/task2/task3 现在改为带用途文字的 01/02/03 目录。",
        "- 旧的 research_bundle / analysis2 命名仍作为概念保留，但主路径以当前目录结构为准。",
        "",
        f"更多说明见: {reports.name}/README.txt 与 {colab.name}/README.txt",
    ]
    (out_root / "README_研究输出说明.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    ap = argparse.ArgumentParser(description="Run eyetrack research output bundle")
    ap.add_argument("--group_manifest", required=True)
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--scenes_root", help="Scene-root mode for fresh batch run")
    src.add_argument("--batch_class_csv", help="Reuse existing batch_aoi_metrics_by_class.csv")

    ap.add_argument("--batch_polygon_csv", default=None, help="Optional existing batch_aoi_metrics_by_polygon.csv when reusing batch outputs")
    ap.add_argument("--scene_features_csv", default=None, help="Optional scene feature table for two-part/modeling extensions; if omitted in --scenes_root mode, it will be auto-generated")
    ap.add_argument("--group_id_col", default="name")
    ap.add_argument("--aoi_json_mode", default="image_stem")
    ap.add_argument("--screen_w", type=int, default=None)
    ap.add_argument("--screen_h", type=int, default=None)
    ap.add_argument("--min_valid_ratio", type=float, default=0.6)
    ap.add_argument("--out_root", default="results/research_bundle")
    args = ap.parse_args()

    out_root = REPO_ROOT / args.out_root
    raw_batch = out_root / RAW_BATCH_DIRNAME
    task1 = out_root / TASK1_DIRNAME
    task2 = out_root / TASK2_DIRNAME
    task3 = out_root / TASK3_DIRNAME
    diag = out_root / DIAG_DIRNAME
    colab = out_root / COLAB_DIRNAME
    reports = out_root / REPORTS_DIRNAME
    for p in [raw_batch, task1, task2, task3, diag, colab, reports]:
        p.mkdir(parents=True, exist_ok=True)

    if args.scenes_root:
        batch_out = raw_batch
        cmd = [
            sys.executable,
            str(SCRIPTS / "batch_aoi_metrics.py"),
            "--group_manifest", args.group_manifest,
            "--scenes_root", args.scenes_root,
            "--aoi_json_mode", args.aoi_json_mode,
            "--unmatched_csv", "error",
            "--outdir", str(batch_out),
            "--dwell_mode", "fixation",
            "--point_source", "fixation",
            "--require_validity",
            "--min_valid_ratio", str(args.min_valid_ratio),
            "--report_time_segments",
            "--report_class_overlap",
            "--export_aoi_overlay",
        ]
        if args.screen_w is not None and args.screen_h is not None:
            cmd += ["--screen_w", str(args.screen_w), "--screen_h", str(args.screen_h), "--image_match", "error"]
        run(cmd)
        class_csv = batch_out / "batch_aoi_metrics_by_class.csv"
        poly_csv = batch_out / "batch_aoi_metrics_by_polygon.csv"
    else:
        class_csv = Path(args.batch_class_csv)
        poly_csv = Path(args.batch_polygon_csv) if args.batch_polygon_csv else None
        if not class_csv.exists():
            raise SystemExit(f"Missing batch_class_csv: {class_csv}")

    cmd = [
        sys.executable,
        str(SCRIPTS / "optimize_aoi_outputs.py"),
        "--aoi_class_csv", str(class_csv),
        "--group_manifest", args.group_manifest,
        "--group_id_col", args.group_id_col,
        "--outdir", str(task1 / "organized_outputs"),
    ]
    if poly_csv and poly_csv.exists():
        cmd += ["--aoi_polygon_csv", str(poly_csv)]
    run(cmd)

    run([
        sys.executable,
        str(SCRIPTS / "summarize_aoi_by_condition_group.py"),
        "--aoi_class_csv", str(class_csv),
        "--group_manifest", args.group_manifest,
        "--group_id_col", args.group_id_col,
        "--outdir", str(task1 / "condition_group_summary"),
        "--include_round",
    ])

    run([
        sys.executable,
        str(SCRIPTS / "model_aoi_lmm_allocation.py"),
        "--aoi_class_csv", str(class_csv),
        "--group_manifest", args.group_manifest,
        "--group_id_col", args.group_id_col,
        "--outdir", str(task2 / "allocation_lmm"),
    ])

    run([
        sys.executable,
        str(SCRIPTS / "plot_aoi_lmm_explanatory.py"),
        "--aoi_class_csv", str(class_csv),
        "--group_manifest", args.group_manifest,
        "--group_id_col", args.group_id_col,
        "--outdir", str(task2 / "allocation_lmm_visuals"),
    ])

    run([
        sys.executable,
        str(SCRIPTS / "aoi_distribution_diagnostics.py"),
        "--aoi_class_csv", str(class_csv),
        "--outdir", str(diag / "distribution"),
    ])

    scene_features_csv = args.scene_features_csv
    autogenerated_scene_features = None
    analysis_csv = None
    if (not scene_features_csv) and args.scenes_root:
        autogenerated_scene_features = out_root / "scene_features_autogenerated.csv"
        run([
            sys.executable,
            str(SCRIPTS / "generate_scene_features.py"),
            "--aoi_class_csv", str(class_csv),
            "--scenes_root", args.scenes_root,
            "--group_manifest", args.group_manifest,
            "--aoi_json_mode", args.aoi_json_mode,
            "--out_csv", str(autogenerated_scene_features),
        ])
        scene_features_csv = str(autogenerated_scene_features)

    if scene_features_csv:
        analysis_csv = out_root / "analysis2_analysis_table.csv"
        run([
            sys.executable,
            str(SCRIPTS / "merge_scene_features.py"),
            "--aoi_class_csv", str(class_csv),
            "--scene_features_csv", str(scene_features_csv),
            "--out_csv", str(analysis_csv),
        ])
        run([
            sys.executable,
            str(SCRIPTS / "model_aoi_two_part.py"),
            "--analysis_csv", str(analysis_csv),
            "--outdir", str(task3 / "two_part_models"),
            "--log1p_ttff",
            "--log1p_tfd",
        ])

    report_note = (
        "Canonical research output bundle for eyetrack.\n"
        "This structure unifies the former research_bundle and AOI-output naming into a clearer hierarchy.\n"
        f"Main reading path: {TASK1_DIRNAME} -> {TASK2_DIRNAME} -> {TASK3_DIRNAME} -> {DIAG_DIRNAME}.\n"
    )
    if autogenerated_scene_features:
        report_note += f"Auto-generated scene_features_csv: {autogenerated_scene_features}\n"
    if analysis_csv:
        report_note += f"Merged analysis table: {analysis_csv}\n"
    (reports / "README.txt").write_text(report_note, encoding="utf-8")

    (colab / "README.txt").write_text(
        "Use scripts/run_colab_one_command.py (or scripts/run_colab_analysis2_pipeline.py) in Colab for mixed-size scene folders.\n"
        "The top-level output folder is now named 研究输出_时间戳, and this directory is the canonical eyetrack output bundle.\n",
        encoding="utf-8",
    )

    write_structure_readme(
        out_root=out_root,
        task1=task1,
        task2=task2,
        task3=task3,
        diag=diag,
        raw_batch=raw_batch,
        reports=reports,
        colab=colab,
        autogenerated_scene_features=autogenerated_scene_features,
        analysis_csv=analysis_csv,
    )

    print("Saved research output bundle to:", out_root)


if __name__ == "__main__":
    main()
